version: "3.0"
services:
  # Reverse proxy를 구현하는 NGINX 서버
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /srv/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443

  # Let's encrypt 자동화 컨테이너
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - acme:/etc/acme.sh
      - /srv/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy

  # 프론트엔드 개발 서버
  frontend-dev:
    image: node:14
    environment:
      - VIRTUAL_HOST=${HOST}
      - LETSENCRYPT_HOST=${HOST}
    volumes:
      - /srv/server-frontend/src:/app
    working_dir: /app
    entrypoint: ["yarn", "start"]
    expose:
      - 3000
    tty: true
    stdin_open: true
    restart: always

  # 백엔드 api 개발 서버
  backend-dev:
    build: /srv/server-backend
    environment:
      - VIRTUAL_HOST=api.${HOST}
      - LETSENCRYPT_HOST=api.${HOST}
      - DEBUG=True
    volumes:
      - /srv/server-backend:/app

  # 백엔드 api express 포팅
  backend-dev-express:
    image: node:14
    environment:
      - VIRTUAL_HOST=express.${HOST}
      - LETSENCRYPT_HOST=express.${HOST}
    volumes:
      - /srv/server-backend-express:/app
    working_dir: /app
    expose:
      - 3000
    entrypoint: ["npm", "start"]


volumes:
  conf:
  vhost:
  html:
  dhparam:
  acme:
